# Fantasy premier league optimizaion

import packages used in the team selection process

In [2]:
from helpers import optimize, read_data

The data is extracted from fantasyfootballscout, where each player is given a projected point for the first 6 gameweeks.

In [3]:
df = read_data(4, 9)

In [4]:
df.head(5)

,player,team,position,price,gw4,gw5,gw6,gw7,gw8,gw9,gw_first_3,gw_all
0,Salah,LIV,MID,12.5,6.5,7.5,6.9,5.1,6.8,5.2,20.9,38.0
1,Mane,LIV,MID,11.9,5.3,6.1,5.6,4.2,5.5,4.3,17.0,31.0
2,Son,TOT,MID,10.1,5.2,4.2,4.6,5.5,5.5,4.8,14.0,29.8
3,Fernandes,MUN,MID,12.0,6.2,4.6,5.3,5.2,4.1,4.3,16.1,29.7
4,Lukaku,CHE,FWD,11.5,5.2,4.1,3.9,5.5,5.0,5.9,13.2,29.6

## Optimize for the first 3 gameweeks with restrictions

We want to limit the number of Manchester City players to one, because of the pep roulette.  
Allow Liverpool to have up to two midfielders.  
Pre-select Salah, Ronaldo and Alexander Arnold.    
Dont want Veltman nor Ben white in defence.

In [17]:
team = optimize(
    df, 'gw_all', budget=100.0, 
    team_restrictions=[('MCI', 1)], 
    position_restrictions=[('LIV', 1, 2, 1, 1)],
    player_selection=[('LIV', 'Salah'), ('MUN', 'Ronaldo'),('LIV', 'Alexander-Arnold') ],
    player_banned=[('BRI', 'Veltman'), ('ARS', 'White')]
)

Optimal

In [18]:
team.sort_values('position')

,player,team,position,price,gw4,gw5,gw6,gw7,gw8,gw9,gw_first_3,gw_all
9,Alexander-Arnold,LIV,DEF,7.5,4.5,6.0,5.2,3.5,5.3,3.5,15.7,28.0
31,Rudiger,CHE,DEF,5.5,4.1,3.0,2.8,4.2,3.9,4.4,9.9,22.4
48,Digne,EVE,DEF,5.4,4.2,3.1,4.3,2.1,3.4,4.2,11.6,21.3
68,Tierney,ARS,DEF,4.9,3.9,3.3,2.8,2.8,3.9,3.4,10.0,20.1
85,Semedo,WOL,DEF,4.9,3.3,3.7,3.0,3.7,2.7,2.5,10.0,18.9
6,Ronaldo,MUN,FWD,12.5,5.8,4.6,5.2,5.2,4.2,4.4,15.6,29.4
7,Antonio,WHM,FWD,7.9,5.0,4.4,4.8,5.8,4.5,4.7,14.2,29.2
22,Pukki,NOR,FWD,5.9,3.6,4.7,3.7,4.0,4.1,3.0,12.0,23.1
40,Sanchez,BRI,GK,4.5,3.7,3.6,3.9,3.6,3.8,3.2,11.2,21.8
50,Guaita,CRY,GK,4.5,3.5,3.1,3.8,3.5,3.3,4.0,10.4,21.2
0,Salah,LIV,MID,12.5,6.5,7.5,6.9,5.1,6.8,5.2,20.9,38.0
26,Benrahma,WHM,MID,6.4,4.0,3.5,3.7,4.5,3.6,3.7,11.2,23.0
28,Sarr,WAT,MID,6.0,4.0,4.1,4.4,3.6,3.2,3.4,12.5,22.7
35,Harrison,LEE,MID,5.9,3.1,3.7,3.7,4.1,3.6,3.9,10.5,22.1
46,Gray,EVE,MID,5.6,4.0,3.3,4.1,2.8,3.5,3.9,11.4,21.6